print("Welcome to the tip calculator")
total_bill = float(input("What was the total bill?   "))
tip_percentage = int(input("What percentage tip would you like to give? 10 ,12 or 15 ?   "))
people = int(input( " How many people to split the bill?   "))
total_tip = total_bill * (tip_percentage / 100 )
each_tip = float(total_tip / people )
each_bill = float(total_bill / people)
each_total = (each_tip + each_bill)
print( "each person have to pay " , each_total)
